#!python3

from bs4 import BeautifulSoup as bs
import requests as rq

while True:

    busca = input("O que deseja pesquisar? (Digite sem acentuação) ")
    busca = busca.replace(" ", '_')
    url = "https://pt.wikipedia.org/wiki/"
    page = rq.get(url=url)
    soup = bs(page.content, 'html.parser')
    conteudo = soup.find(class_="mw-parser-output")
    texto = conteudo.get_text()

    print(texto)
    
    #Esta parte é para salvar o conteúdo da variável texto num arquivo txt
    with open(busca+'.txt', 'wb') as f:
        f.write(texto.encode())
    f.close()
